version: '3'

services:
  node-app:
    build: .
    image: arnw/cloud-devops-rest-api
    environment:
      - DOCKER_VOLUMES_USERS=/usr/src/cloud-devops-rest-api
      - MONGODB_URL=mongodb://admin:passpass666@34.122.246.86:27017/cloud-devops-restful-api
    ports:
      - '3000:3000'
    depends_on:
      - arnw/git-server
    volumes:
      - .:/usr/src/cloud-devops-rest-api
    networks:
      - node-api-network

  git:
    image: arnw/git-server
    ports:
      - '7005:7005'
    volumes:
      - dbdata:/data/db
    networks:
      - node-api-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
