 version: "3.8"
services:
  mongodb:
    image : mongo:4.4
    container_name: cloud-devops-mongodb
    hostname: cloud-devops-mongodb
    volumes:
      - /home/arno/mongodb/database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: cloud-devops-restful-api
      MONGO_INITDB_USERNAME: user1
      MONGO_INITDB_PASSWORD: passpass666
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - network-ext
  cloud-devops-rest-api:
    image: arnw/lpcloud-rest-api-arm64:latest
    container_name: cloud-devops-rest-api
    hostname: cloud-devops-rest-api
    environment:
      DOCKER_VOLUMES_USERS: /usr/src/cloud-devops-rest-api
      MONGODB_URL: mongodb://admin:passpass666@34.122.246.86:27017/cloud-devops-restful-api
      JWT_SECRET: thisisasamplesecret
      JWT_ACCESS_EXPIRATION_MINUTES: 180
      JWT_REFRESH_EXPIRATION_DAYS: 30
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10
      SMTP_HOST: smtp.ethereal.email
      SMTP_PORT: 587
      SMTP_USERNAME: brandyn.mccullough81@ethereal.email
      SMTP_PASSWORD: WxyzxY6MWFUB3YSuKQ
      EMAIL_FROM: support@yourapp.com
    command: npm run dev
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - network-ext
      - network-int
  gitea:
    image: gitea/gitea:latest
    container_name: cloud-devops-gitea
    hostname: cloud-devops-gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    networks:
      - network-ext
    volumes:
      - /var/lib/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    restart: unless-stopped
networks:
  network-ext:
  network-int:
    internal: true
